VIDEO_PATH = "JQVK8688.MP4"

ROI_X = 50
ROI_Y = 150
ROI_W = 400
ROI_H = 300

MIN_CONFIDENCE_COUNT = 0.50
MIN_CONFIDENCE_SAVE = 0.80

COOLDOWN_DETECTION = 1.0
COOLDOWN_SAVE = 10.0
COOLDOWN_PRINT = 3.0

OUTPUT_DIR = "detected_events"
CSV_PATH = "event_log.csv"
CLIPS_DIR = "event_clips"
VIDEO_OUTPUT_DIR = "event_clips"

SAVE_CLIPS = True
PRE_EVENT_SECONDS = 5
POST_EVENT_SECONDS = 5